/***** BEGIN LICENSE BLOCK *****

The contents of this file are subject to the Mozilla Public License
Version 1.1 (the "License"); you may not use this file except in
compliance with the License. You may obtain a copy of the License at
http://www.mozilla.org/MPL/

Software distributed under the License is distributed on an "AS IS"
basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See the
License for the specific language governing rights and limitations
under the License.

The Original Code is GLaxstar Ltd code.

The Initial Developer of the Original Code is Glaxstar Ltd.
Portions created by the Initial Developer are
Copyright (C) 2008 Digg Inc. All Rights Reserved.

Contributor(s):
  Jose Enrique Bolanos <jose@glaxstar.com>
  Andres Hernandez <andres@glaxstar.com>
  Erik van Eykelen <erik@glaxstar.com>

***** END LICENSE BLOCK *****/

#include "nsISupports.idl"

interface gsICMTransferObject;
interface nsIArray;

/**
 * Container DTO
 * Stores container info
 */
[scriptable, uuid(81AF1952-3FFF-42CB-846B-8B2F14B75E9B)]
interface gsIDiggContainerDTO : nsISupports
{
  /* Container name */
  attribute AUTF8String name;
  /* Container short name */
  attribute AUTF8String shortName;
  /* Container topic list */
  attribute nsIArray topics;

  /**
   * Populates the containerDTO with the information contained in the
   * gsICMTransferObject.
   * @param aCMTransferObject the transfer object to extract the container data.
   */
  void populateFromTO(in gsICMTransferObject aCMTransferObject);
};
