/***** BEGIN LICENSE BLOCK *****

Copyright (c) 2008, Digg Inc.
All rights reserved.

Redistribution and use in source and binary forms, with or without modification,
are permitted provided that the following conditions are met:

* Redistributions of source code must retain the above copyright notice, this
list of conditions and the following disclaimer.
* Redistributions in binary form must reproduce the above copyright notice,
this list of conditions and the following disclaimer in the documentation and/or
other materials provided with the distribution.
* Neither the name of Digg Inc. nor the names of its contributors may be used to
endorse or promote products derived from this software without specific prior
written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR
ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

***** END LICENSE BLOCK *****/

#include "nsISupports.idl"
interface gsIDiggLoadHandler;
interface gsIDiggEvent;

/**
 * Event Manager. Fetches events (stories, friend activity) and provides methods
 * to retrieve them.
 */
[scriptable, uuid(D198DE73-FF40-4853-8CF9-A2F61335BF61)]
interface gsIDiggEventManager : nsISupports
{
  /* Observer topic used to notify when the event count changes */
  readonly attribute AUTF8String OBSERVER_TOPIC_EVENT_COUNT_CHANGED;

  /**
   * Fetches new events (stories, friend activity). The result is passed in the
   * load handler ("true" if new events were found, "false" otherwise).
   * @param aLoadHandler The caller's load handler.
   */
  void fetchNewEvents(in gsIDiggLoadHandler aLoadHandler);

  /**
   * Gets the event at the given index.
   * @param aIndex The index of the event to get. If null, zero is assumed.
   * @return An event object. Null if there isn't any.
   */
  gsIDiggEvent getEventAtIndex(in short aIndex);

  /**
   * Obtains the current number of available events.
   * @return The number of events.
   */
  unsigned short getEventCount();
};
