/**
 * Copyright © 2007-2008 Glaxstar Ltd. All rights reserved.
 */

#include "nsISupports.idl"

interface gsICMTransferObject;

/**
 * Load handler for API calls.
 */
[scriptable, uuid(93B521BF-F2A8-49D2-9980-D4391EB01261)]
interface gsICMLoadHandler : nsISupports
{
  /**
   * Handles the load event for an API request.
   * @param aResult the resulting object from the response.
   */
   void handleLoad(in gsICMTransferObject aResult);
};
