/***** BEGIN LICENSE BLOCK *****

The contents of this file are subject to the Mozilla Public License
Version 1.1 (the "License"); you may not use this file except in
compliance with the License. You may obtain a copy of the License at
http://www.mozilla.org/MPL/

Software distributed under the License is distributed on an "AS IS"
basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See the
License for the specific language governing rights and limitations
under the License.

The Original Code is GLaxstar Ltd code.

The Initial Developer of the Original Code is Glaxstar Ltd.
Portions created by the Initial Developer are
Copyright (C) 2008 Digg Inc. All Rights Reserved.

Contributor(s):
  Jose Enrique Bolanos <jose@glaxstar.com>
  Andres Hernandez <andres@glaxstar.com>
  Erik van Eykelen <erik@glaxstar.com>

***** END LICENSE BLOCK *****/

#include "nsISupports.idl"
interface gsICMTransferObject;

/**
 * AdminMessageDTO
 * Stores the information of an administration message.
 */
[scriptable, uuid(5552DBB6-4F91-4AA0-8F0E-BFC5FCFC85E9)]
interface gsIDiggAdminMessageDTO : nsISupports
{
  /* Id of the message */
  attribute unsigned long messageId;
  /* Date of the message */
  attribute unsigned long date;
  /* Title of the message */
  attribute AUTF8String title;
  /* Description of the message */
  attribute AUTF8String description;
  /* Target URL of the message */
  attribute AUTF8String url;

  /**
   * Populates the AdminMessageDTO with the information contained in the
   * gsICMTransferObject.
   * @param aCMTransferObject The transfer object from which to extract the
   * message data.
   */
  void populateFromTO(in gsICMTransferObject aCMTransferObject);
};
