/***** BEGIN LICENSE BLOCK *****

Copyright (c) 2008, Digg Inc.
All rights reserved.

Redistribution and use in source and binary forms, with or without modification,
are permitted provided that the following conditions are met:

* Redistributions of source code must retain the above copyright notice, this
list of conditions and the following disclaimer.
* Redistributions in binary form must reproduce the above copyright notice,
this list of conditions and the following disclaimer in the documentation and/or
other materials provided with the distribution.
* Neither the name of Digg Inc. nor the names of its contributors may be used to
endorse or promote products derived from this software without specific prior
written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR
ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

***** END LICENSE BLOCK *****/

#include "nsISupports.idl"
interface gsICMTransferObject;

/**
 * Comment DTO
 * Stores comment info
 */
[scriptable, uuid(15581382-3B51-4773-92FE-FB62963A53B1)]
interface gsIDiggCommentDTO : nsISupports
{
  /* Id of the comment */
  attribute unsigned long commentId;
  /* Date in which the comment was made */
  attribute unsigned long date;
  /* Id of the story the comment belongs to */
  attribute AUTF8String storyId;
  /* User name of the user who made the comment */
  attribute AUTF8String userName;
  /* Content of the comment */
  attribute AUTF8String content;
  /* Number of thumbs up */
  attribute unsigned short up;
  /* Number of thumbs down */
  attribute unsigned short down;
  /* Number of replies */
  attribute unsigned short replies;
  /* Id of the comment thread root */
  attribute unsigned long threadRootId;

  /**
   * Populates the commentDTO with the information contained in the
   * gsICMTransferObject.
   * @param aCMTransferObject the transfer object to extract the comment data.
   */
  void populateFromTO(in gsICMTransferObject aCMTransferObject);
};
